# Generated by Django 6.0 on 2026-04-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_search_vector_post_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
