# Generated by Django 5.0.14 on 2026-02-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='why_i_wrote_this',
            field=models.TextField(blank=True, help_text='Short explanation of why this post exists.', null=True),
        ),
    ]
